In [3]:
import numpy as numpy
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [4]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [5]:
df.drop_duplicates(subset=['review'], keep='first', inplace=True)
df.reset_index(drop=True, inplace=True)

In [6]:
df.shape

(49582, 2)

In [7]:
df.tail()

                                                  review sentiment
49577  I thought this movie did a down right good job...  positive
49578  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49579  I am a Catholic taught in parochial elementary...  negative
49580  I'm going to have to disagree with the previou...  negative
49581  No one expects the Star Trek movies to be high...  negative

In [9]:
df["review"] = df["review"].str.lower()
df["review"] = df["review"].str.replace(r"<.*?>", "", regex=True)

In [10]:

encoded=LabelEncoder()
y=encoded.fit_transform(df['sentiment'])

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df['review'], y, test_size=0.3, random_state=61)

In [12]:
vectorizer = TfidfVectorizer(
    lowercase=True, 
    stop_words='english',
    ngram_range=(1, 4),
    token_pattern=r'\b[a-zA-Z]{3,}\b', 
    min_df=5,
)
X_train=vectorizer.fit_transform(X_train)
X_test=vectorizer.transform(X_test)

In [13]:
X_train.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
model=MultinomialNB()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nAccuracy Score:", str(accuracy_score(y_test, y_pred)*100)+'%')

Confusion Matrix:
 [[6473  979]
 [ 779 6644]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.87      0.88      7452
           1       0.87      0.90      0.88      7423

    accuracy                           0.88     14875
   macro avg       0.88      0.88      0.88     14875
weighted avg       0.88      0.88      0.88     14875


Accuracy Score: 88.18151260504202%