In [31]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [32]:
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/IMDB Dataset.csv')
df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [33]:
df.tail(20)

                                                  review sentiment
49980  A stunning film of high quality.<br /><br />Ap...  positive
49981  And I repeat, please do not see this movie! Th...  negative
49982  To be hones, I used to like this show and watc...  negative
49983  I loved it, having been a fan of the original ...  positive
49984  Hello it is I Derrick Cannon and I welcome you...  negative
49985  Imaginary Heroes is clearly the best film of t...  positive
49986  This movie is a disgrace to the Major League F...  negative
49987  A remake of Alejandro Amenabar's Abre los Ojos...  negative
49988  When I first tuned in on this morning news, I ...  negative
49989  I got this one a few weeks ago and love it! It...  positive
49990  Lame, lame, lame!!! A 90-minute cringe-fest th...  negative
49991  Les Visiteurs, the first movie about the medie...  negative
49992  John Garfield plays a Marine who is blinded by...  positive
49993  Robert Colomb has two full-time jobs. He's kno...  negative
49994  This is your typical junk comedy.<br /><br />T...  negative
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

In [35]:
df.duplicated().sum().item()

418

In [36]:
df.drop_duplicates(subset=['review'], keep='first', inplace=True)
df.reset_index(drop=True, inplace=True)
df.head(20)

                                               review sentiment
0   One of the other reviewers has mentioned that ...  positive
1   A wonderful little production. <br /><br />The...  positive
2   I thought this was a wonderful way to spend ti...  positive
3   Basically there's a family where a little boy ...  negative
4   Petter Mattei's "Love in the Time of Money" is...  positive
5   Probably my all-time favorite movie, a story o...  positive
6   I sure would like to see a resurrection of a u...  positive
7   This show was an amazing, fresh & innovative i...  negative
8   Encouraged by the positive comments about this...  negative
9   If you like original gut wrenching laughter yo...  positive
10  Phil the Alien is one of those quirky films wh...  negative
11  I saw this movie when I was about 12 when it c...  negative
12  So im not a big fan of Boll's work but then ag...  negative
13  The cast played Shakespeare.<br /><br />Shakes...  negative
14  This a fantastic movie of three prisoners who ...  positive
15  Kind of drawn in by the erotic scenes, only to...  negative
16  Some films just simply should not be remade. T...  positive
17  This movie made it into one of my top 10 most ...  negative
18  I remember this film,it was the first film i h...  positive
19  An awful film! It must have been up against so...  negative

In [37]:
df["review"] = df["review"].str.lower()
df["review"] = df["review"].str.replace(r"<.*?>", "", regex=True)

In [38]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production. the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there's a family where a little boy ...  negative
4  petter mattei's "love in the time of money" is...  positive

In [39]:
X=df["review"]
y=df["sentiment"]

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=61)

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
vectorizer = CountVectorizer(
    lowercase=True, 
    stop_words='english',
    ngram_range=(1, 2),
    token_pattern=r'\b[a-zA-Z]{3,}\b', 
    min_df=5,
)
X_train=vectorizer.fit_transform(X_train)
X_test=vectorizer.transform(X_test)

In [43]:
vectorizer.vocabulary_

{'working': 102285,
 'way': 99967,
 'collection': 15198,
 'lugosi': 55560,
 'films': 32689,
 'recently': 75202,
 'having': 40847,
 'just': 47305,
 'blown': 8733,
 'away': 5066,
 'couple': 17542,
 'days': 19351,
 'ago': 2181,
 'combination': 15322,
 'boris': 9356,
 'karloff': 48217,
 'black': 8343,
 'cat': 12005,
 'really': 74480,
 'looking': 54381,
 'forward': 34261,
 'seeing': 81136,
 'collaboration': 15178,
 'raven': 73976,
 'alas': 2409,
 'didn': 21356,
 'work': 102056,
 'end': 25956,
 'film': 30768,
 'quite': 73252,
 'disappointed': 22329,
 'quarters': 73108,
 'movie': 60535,
 'thought': 92285,
 'story': 87380,
 'lacked': 49840,
 'real': 74161,
 'suspense': 89679,
 'doing': 23396,
 'pretty': 71612,
 'good': 37473,
 'job': 46706,
 'holding': 42293,
 'things': 91627,
 'somewhat': 85109,
 'mad': 55729,
 'sort': 85391,
 'surgical': 89525,
 'genius': 35900,
 'falls': 29154,
 'love': 55021,
 'young': 103643,
 'woman': 101517,
 'irene': 45777,
 'ware': 99011,
 'treats': 94620,
 'car': 11364,
 'accident': 369,
 'partly': 67185,
 'engaged': 26446,
 'father': 29864,
 'samuel': 78733,
 'hinds': 42015,
 'disapproves': 22377,
 'deal': 19508,
 'situation': 84157,
 'enlists': 26687,
 'aid': 2277,
 'edmond': 25226,
 'bateman': 6311,
 'horribly': 42864,
 'ugly': 95776,
 'man': 56789,
 'wants': 98848,
 'make': 56023,
 'look': 54185,
 'acceptable': 354,
 'aside': 4226,
 'performance': 68306,
 'little': 53343,
 'hold': 42275,
 'suddenly': 88917,
 'minutes': 59344,
 'shifts': 82866,
 'completely': 16183,
 'suspenseful': 89712,
 'fell': 30382,
 'apart': 3583,
 'largely': 50111,
 'tried': 94709,
 'shift': 82863,
 'insane': 44910,
 'difference': 21583,
 'plays': 69822,
 'role': 77616,
 'controlled': 16976,
 'control': 16967,
 'evil': 27659,
 'think': 91787,
 'pulled': 72773,
 'point': 70419,
 'offers': 65335,
 'maniacal': 57208,
 'laughter': 50473,
 'comes': 15686,
 'fake': 29094,
 'meantime': 58245,
 'huge': 43288,
 'disappointment': 22366,
 'grabbed': 38454,
 'grated': 38607,
 'movies': 62369,
 'star': 86514,
 'gets': 36098,
 'billing': 8052,
 'clearly': 14712,
 'lead': 50574,
 'actor': 1018,
 'surely': 89498,
 'gives': 36729,
 'hint': 42023,
 'universal': 96451,
 'ranked': 73758,
 'great': 38647,
 'horror': 42884,
 'stars': 86605,
 'inexplicably': 44686,
 'add': 1688,
 'better': 7451,
 'event': 27545,
 'connection': 16618,
 'edgar': 25143,
 'allen': 2581,
 'poe': 70400,
 'fanatic': 29454,
 'tries': 94744,
 'recreate': 75376,
 'torture': 94023,
 'techniques': 90649,
 'stories': 87337,
 'overall': 66431,
 'working way': 102309,
 'films recently': 32947,
 'having just': 40884,
 'just blown': 47370,
 'blown away': 8734,
 'couple days': 17550,
 'days ago': 19352,
 'boris karloff': 9357,
 'black cat': 8355,
 'really looking': 74752,
 'looking forward': 54420,
 'forward seeing': 34275,
 'alas just': 2410,
 'just didn': 47470,
 'didn work': 21529,
 'work end': 102100,
 'end film': 26028,
 'film quite': 32040,
 'quite disappointed': 73297,
 'quarters movie': 73110,
 'movie thought': 62161,
 'thought story': 92411,
 'story lacked': 87690,
 'lacked real': 49842,
 'real suspense': 74347,
 'doing pretty': 23436,
 'pretty good': 71682,
 'good job': 37741,
 'falls love': 29169,
 'love young': 55313,
 'young woman': 103774,
 'car accident': 11365,
 'enlists aid': 26688,
 'man wants': 57098,
 'make look': 56223,
 'performance little': 68369,
 'minutes movie': 59414,
 'fell apart': 30383,
 'movie tried': 62205,
 'plays mad': 69865,
 'didn think': 21511,
 'maniacal laughter': 57209,
 'just comes': 47419,
 'huge disappointment': 43297,
 'movies star': 62674,
 'gets billing': 36113,
 'lead actor': 50575,
 'gives hint': 36755,
 'great horror': 38826,
 'horror stars': 42945,
 'better actor': 7456,
 'real connection': 74188,
 'edgar allen': 25145,
 'allen poe': 2585,
 'poe story': 70401,
 'sleeper': 84402,
 'cell': 12234,
 'attempts': 4581,
 'swim': 89855,
 'sides': 83581,
 'pool': 70732,
 'terrorism': 91147,
 'patriotic': 67418,
 'muslim': 63193,
 'americans': 2977,
 'does': 22888,
 'watching': 99710,
 'long': 54024,
 'time': 92697,
 'feeling': 30288,
 'predictable': 71377,
 'year': 103317,
 'netflix': 63925,
 'queue': 73176,
 'finally': 33128,
 'moved': 60503,
 'undercover': 95994,
 'fbi': 30074,
 'attempt': 4540,
 'infiltrate': 44724,
 'terrorist': 91148,
 'operating': 65846,
 'united': 96442,
 'states': 86851,
 'agent': 2158,
 'actually': 1420,
 'conflict': 16545,
 'resolution': 76397,
 'patriotism': 67420,
 'religious': 75879,
 'beliefs': 6835,
 'personally': 68701,
 'watched': 99619,
 'drama': 24028,
 'american': 2868,
 'family': 29211,
 'living': 53774,
 'doubtful': 23915,
 'america': 2850,
 'channel': 12632,
 'cable': 10851,
 'network': 63929,
 'produce': 72216,
 'shows': 83366,
 'muslims': 63195,
 'flattering': 33547,
 'light': 51749,
 'lot': 54738,
 'friends': 34689,
 'honestly': 42591,
 'say': 79117,
 'terrorists': 91153,
 'close': 14886,
 'busting': 10746,
 'stereotypes': 87058,
 'focuses': 33827,
 'worse': 102541,
 'episode': 27005,
 'honor': 42624,
 'killing': 48812,
 'poor': 70739,
 'portrayal': 70975,
 'islam': 45869,
 'respected': 76431,
 'moderate': 59769,
 'scholar': 80212,
 'teaching': 90554,
 'viewer': 97791,
 'jihad': 46637,
 'personal': 68660,
 'struggle': 88354,
 'meant': 58225,
 'violence': 98002,
 'main': 55866,
 'character': 12679,
 'need': 63686,
 'learn': 50668,
 'helps': 41539,
 'bit': 8136,
 'far': 29602,
 'short': 83031,
 'giving': 36794,
 'audience': 4698,
 'needs': 63787,
 'knows': 49552,
 'said': 78534,
 'acting': 570,
 'superb': 89142,
 'extremely': 28514,
 'engrossing': 26525,
 'rate': 73859,
 'sleeper cell': 84403,
 'watching long': 99807,
 'long time': 54148,
 'time feeling': 92880,
 'man working': 57115,
 'united states': 96446,
 'undercover agent': 95995,
 'religious beliefs': 75880,
 'personally watched': 68720,
 'american family': 2901,
 'family living': 29271,
 'cable network': 10858,
 'honestly say': 42603,
 'comes close': 15698,
 'main character': 55876,
 'need learn': 63712,
 'learn lot': 50683,
 'helps little': 41541,
 'little bit': 53360,
 'comes far': 15717,
 'far short': 29706,
 'audience really': 4770,
 'really needs': 74788,
 'said acting': 78535,
 'acting superb': 827,
 'anthony': 3469,
 'park': 67050,
 'glenn': 36892,
 'want': 98585,
 'creation': 18001,
 'amber': 2818,
 'alert': 2460,
 'poorly': 70828,
 'terrible': 91034,
 'major': 55971,
 'problem': 72119,
 'involved': 45710,
 'second': 80978,
 'half': 39989,
 'nichole': 64301,
 'events': 27553,
 'surrounding': 89625,
 'entirely': 26916,
 'correct': 17286,
 'suffering': 88947,
 'psychological': 72683,
 'disorders': 22587,
 'picked': 69020,
 'intent': 45243,
 'harm': 40630,
 'loved': 55318,
 'like': 51823,
 'daughter': 19111,
 'mindset': 59235,
 'rescuing': 76344,
 'neglect': 63843,
 'likely': 52966,
 'believed': 6970,
 'coming': 15819,
 'mother': 60354,
 'paid': 66759,
 'attention': 4607,
 'plus': 70363,
 'years': 103375,
 'took': 93907,
 'care': 11419,
 'summarily': 89042,
 'raised': 73629,
 'frolic': 34808,
 'depicted': 20376,
 'manner': 57245,
 'going': 37178,
 'shape': 82692,
 'form': 34197,
 'funny': 35067,
 'thing': 91402,
 'spent': 85939,
 'nights': 64466,
 'fathers': 29941,
 'place': 69337,
 'sharon': 82728,
 'reason': 75006,
 'originally': 66207,
 'violent': 98034,
 'items': 46105,
 'conceived': 16401,
 'weapons': 100483,
 'truck': 94905,
 'deemed': 19933,
 'tools': 93953,
 'kept': 48407,
 'recommendation': 75323,
 'grain': 38515,
 'salt': 78681,
 'based': 6173,
 'true': 94915,
 'details': 20684,
 'portion': 70958,
 'inaccurate': 44340,
 'depict': 20375,
 'failure': 29010,
 'director': 22016,
 'discover': 22443,
 'truth': 95129,
 'telling': 90855,
 'interviewed': 45544,
 'knew': 49110,
 'stated': 86839,
 'exactly': 27750,
 'posted': 71117,
 'father want': 29931,
 'want say': 98719,
 'say story': 79330,
 'story movie': 87741,
 'good movie': 37823,
 'movie poorly': 61719,
 'acting terrible': 837,
 'major problem': 55997,
 'problem movie': 72148,
 'movie involved': 61383,
 'second half': 81010,
 'events surrounding': 27585,
 'story entirely': 87556,
 'loved like': 55338,
 'like daughter': 52052,
 'little attention': 53352,
 'plus years': 70382,
 'took care': 93913,
 'movie depicted': 60941,
 'harm way': 40632,
 'way shape': 100284,
 'shape form': 82693,
 'funny thing': 35255,
 'originally thought': 66223,
 'time work': 93320,
 'grain salt': 38516,
 'good story': 37968,
 'story based': 87410,
 'based true': 6218,
 'true events': 94944,
 'details movie': 20690,
 'discover truth': 22447,
 'telling story': 90862,
 'story funny': 87607,
 'thing director': 91444,
 'basic': 6233,
 'message': 58716,
 'strong': 88268,
 'survive': 89636,
 'psychically': 72673,
 'emotionally': 25857,
 'sensitive': 81835,
 'leave': 50723,
 'hole': 42310,
 'lives': 53728,
 'seen': 81224,
 'finality': 33127,
 'selfish': 81648,
 'phoebe': 68911,
 'realizes': 74475,
 'prior': 71907,
 'helping': 41531,
 'wolf': 101505,
 'heal': 41080,
 'self': 81581,
 'blame': 8469,
 'accept': 347,
 'closure': 14963,
 'missing': 59621,
 'sister': 84082,
 'beautiful': 6485,
 'european': 27491,
 'scenery': 79870,
 'idealism': 43820,
 'addiction': 1738,
 'big': 7816,
 'moment': 59869,
 'gang': 35517,
 'early': 24856,
 'liked': 52911,
 'reflected': 75539,
 'came': 10989,
 'age': 2110,
 'way away': 99989,
 'lives love': 53752,
 'end just': 26060,
 'just prior': 47827,
 'missing sister': 59637,
 'lot truth': 54914,
 'big moment': 7914,
 'moment moment': 59885,
 'moment thought': 59896,
 'liked movie': 52938,
 'time came': 92751,
 'muscular': 62984,
 'scientists': 80371,
 'unpleasantly': 96603,
 'females': 30498,
 'swimsuits': 89862,
 'lots': 54927,
 'beer': 6664,
 'drinking': 24267,
 'commercial': 15946,
 'okay': 65392,
 'plot': 69977,
 'shark': 82716,
 'monster': 60124,
 'people': 67692,
 'stuff': 88439,
 'haven': 40820,
 'beer drinking': 6666,
 'plot big': 69997,
 'like monster': 52446,
 'killing people': 48823,
 'haven seen': 40839,
 'hallmark': 40080,
 'opinion': 65858,
 'started': 86719,
 'decent': 19717,
 'eventually': 27590,
 'got': 38209,
 'sour': 85581,
 'soldier': 85020,
 'afghanistan': 2066,
 'receives': 75182,
 'christmas': 14137,
 'cards': 11418,
 'sent': 81843,
 'troops': 94864,
 'inspired': 44998,
 'card': 11404,
 'feels': 30342,
 'given': 36650,
 'ray': 73993,
 'hope': 42672,
 'happiness': 40410,
 'life': 51364,
 'motivation': 60443,
 'continue': 16898,
 'goes': 37056,
 'town': 94252,
 'spunky': 86247,
 'finds': 33218,
 'meets': 58350,
 'saving': 78965,
 'dad': 18739,
 'vietnam': 97758,
 'war': 98912,
 'veteran': 97605,
 'getting': 36255,
 'hit': 42141,
 'whilst': 100849,
 'crossing': 18324,
 'street': 88156,
 'decides': 19839,
 'doesn': 23169,
 'home': 42457,
 'agrees': 2257,
 'help': 41447,
 'season': 80925,
 'logging': 53967,
 'company': 16031,
 'vice': 97639,
 'versa': 97500,
 'relationship': 75737,
 'distance': 22664,
 'boyfriend': 9586,
 'different': 21591,
 'prefers': 71437,
 'wine': 101289,
 'trips': 94826,
 'france': 34366,
 'hard': 40456,
 'labor': 49756,
 'outdoors': 66333,
 'rest': 76465,
 'triangle': 94681,
 'visiting': 98121,
 'mom': 59862,
 'basically': 6248,
 'best': 7151,
 'spoiler': 86106,
 'common': 15982,
 'happen': 40278,
 'spend': 85899,
 'gradually': 38499,
 'attracted': 4659,
 'persona': 68655,
 'day': 19231,
 'kisses': 49060,
 'confused': 16567,
 'marry': 57486,
 'someday': 85100,
 'fond': 33942,
 'soon': 85276,
 'know': 49186,
 'kiss': 49056,
 'protective': 72550,
 'thinks': 92211,
 'trying': 95240,
 'propose': 72507,
 'accepts': 363,
 'plans': 69521,
 'marriage': 57462,
 'kids': 48591,
 'travel': 94556,
 'world': 102354,
 'exotic': 28135,
 'places': 69443,
 'sound': 85456,
 'thrilling': 92526,
 'bad': 5413,
 'despite': 20612,
 'urging': 96846,
 'stay': 86888,
 'head': 40990,
 'eve': 27535,
 'service': 82205,
 'church': 14213,
 'hasn': 40713,
 'left': 50847,
 'speak': 85747,
 'outside': 66375,
 'broken': 10163,
 'hearted': 41220,
 'let': 51117,
 'breaks': 9770,
 'ends': 26376,
 'nice': 64182,
 'polite': 70651,
 'sense': 81720,
 'moments': 59902,
 'participating': 67111,
 'charitable': 13440,
 'causes': 12154,
 'hands': 40217,
 'pray': 71310,
 'evening': 27540,
 'meal': 58091,
 'table': 89995,
 'lasting': 50169,
 'evidently': 27657,
 'healthy': 41090,
 'right': 77089,
 'did': 21053,
 'wrong': 103109,
 'don': 23526,
 'typical': 95720,
 'turns': 95524,
 'slowly': 84568,
 'subtly': 88810,
 'moves': 60517,
 'practically': 71274,
 'applauds': 3750,
 'behavior': 6796,
 'participates': 67110,
 'services': 82210,
 'act': 499,
 'language': 50044,
 'conclusion': 16454,
 'ran': 73697,
 'ended': 26219,
 'fast': 29804,
 'forwarding': 34282,
 'gem': 35788,
 'ruining': 78182,
 'recommend': 75270,
 'watched film': 99647,
 'hallmark channel': 40081,
 'opinion film': 65870,
 'film started': 32289,
 'eventually got': 27606,
 'ray hope': 73999,
 'goes town': 37160,
 'woman lives': 101574,
 'lives comes': 53734,
 'eventually finds': 27603,
 'vietnam war': 97763,
 'war veteran': 98992,
 'getting hit': 36285,
 'hit car': 42144,
 'crossing street': 18328,
 'family home': 29257,
 'agrees help': 2258,
 'help family': 41464,
 'family christmas': 29222,
 'christmas season': 14152,
 'comes love': 15743,
 'vice versa': 97642,
 'love family': 55100,
 'family daughter': 29225,
 'relationship man': 75757,
 'man love': 56967,
 'love long': 55174,
 'long distance': 54043,
 'hard labor': 40510,
 'great outdoors': 38906,
 'rest film': 76482,
 'film love': 31740,
 'love triangle': 55287,
 'wants best': 98852,
 'spoiler alert': 86108,
 'woman comes': 101534,
 'comes like': 15740,
 'like soldier': 52698,
 'lot common': 54760,
 'spend lot': 85910,
 'lot time': 54911,
 'love boyfriend': 55048,
 'wants marry': 98881,
 'doesn know': 23258,
 'woman thinks': 101615,
 'wants wants': 98906,
 'wants home': 98873,
 'close family': 14898,
 'family wants': 29329,
 'doesn sound': 23323,
 'bad doesn': 5500,
 'doesn want': 23348,
 'want make': 98684,
 'make things': 56333,
 'things worse': 91781,
 'decides leave': 19851,
 'leave town': 50762,
 'christmas eve': 14144,
 'film ends': 31284,
 'getting things': 36327,
 'things like': 91709,
 'like like': 52372,
 'film basically': 30901,
 'strong sense': 88309,
 'doing good': 23416,
 'good moments': 37817,
 'family going': 29252,
 'going church': 37200,
 'hold hands': 42283,
 'dad mom': 18745,
 'long lasting': 54081,
 'right thing': 77230,
 'did wrong': 21350,
 'wrong things': 103176,
 'things don': 91664,
 'don like': 23634,
 'like typical': 52813,
 'typical love': 95736,
 'triangle story': 94682,
 'story film': 87590,
 'family goes': 29251,
 'act bad': 500,
 'bad language': 5589,
 'disappointed film': 22338,
 'film ran': 32042,
 'got worse': 38390,
 'worse worse': 102598,
 'fast forwarding': 29813,
 'film film': 31389,
 'don recommend': 23686,
 'recommend film': 75288,
 'grease': 38645,
 'crack': 17790,
 'shameful': 82666,
 'euphoric': 27478,
 'powerfully': 71256,
 'addictive': 1740,
 'experience': 28263,
 'watch': 99289,
 'rewind': 76841,
 'passed': 67274,
 'hostile': 42997,
 'stand': 86425,
 'old': 65430,
 'girl': 36460,
 'reviewed': 76748,
 'brilliant': 9933,
 'fun': 34904,
 'original': 66056,
 'fledgling': 33587,
 'adolescent': 1866,
 'hormones': 42791,
 'assured': 4403,
 'unyielding': 96770,
 'fixation': 33456,
 'utter': 97140,
 'rubbish': 78127,
 'pass': 67257,
 'absolutely': 208,
 'excuse': 28036,
 'suggest': 88964,
 'inane': 44347,
 'artless': 4166,
 'slipshod': 84491,
 'embarrassment': 25742,
 'participated': 67109,
 'production': 72268,
 'distribution': 22712,
 'consumption': 16817,
 'sake': 78641,
 'criticism': 18248,
 'dignify': 21780,
 'explaining': 28336,
 'blows': 8736,
 'executed': 28053,
 'musical': 63156,
 'songs': 85229,
 'advance': 1948,
 'narrative': 63419,
 'develop': 20761,
 'characters': 13020,
 'debatable': 19650,
 'exceptions': 27971,
 'music': 62996,
 'obscenely': 65090,
 'pointless': 70534,
 'appear': 3690,
 'relate': 75719,
 'innuendo': 44897,
 'sex': 82436,
 'excessive': 27976,
 'general': 35819,
 'score': 80395,
 'tonight': 93882,
 'reproduction': 76297,
 'country': 17511,
 'making': 56574,
 'concrete': 16477,
 'statement': 86843,
 'themes': 91344,
 'uncomfortably': 95940,
 'stupid': 88531,
 'cast': 11777,
 'demonstrates': 20290,
 'semblance': 81673,
 'ability': 52,
 'sing': 83948,
 'dance': 18839,
 'birds': 8114,
 'badass': 5795,
 'likable': 51814,
 'instead': 45031,
 'annoying': 3391,
 'loser': 54638,
 'johnny': 46947,
 'michael': 58814,
 'sacred': 78404,
 'bird': 8110,
 'jacket': 46170,
 'initiates': 44833,
 'kick': 48509,
 'ground': 39322,
 'spit': 86041,
 'duck': 24456,
 'scrub': 80846,
 'body': 8858,
 'touched': 94177,
 'course': 17609,
 'gold': 37387,
 'fact': 28773,
 'bunch': 10591,
 'bumbling': 10579,
 'greater': 39068,
 'smart': 84675,
 'kind': 48863,
 'resourceful': 76416,
 'average': 4955,
 'impotence': 44266,
 'notwithstanding': 64833,
 'feasible': 30094,
 'stephanie': 87023,
 'ultimately': 95808,
 'embrace': 25761,
 'reveals': 76677,
 'mask': 57587,
 'hand': 40153,
 'slovenly': 84521,
 'slack': 84307,
 'jawed': 46416,
 'bubble': 10336,
 'gum': 39572,
 'smacking': 84604,
 'dirty': 22289,
 'wearing': 100489,
 'rude': 78145,
 'trashy': 94542,
 'guess': 39442,
 'harbors': 40454,
 'characteristics': 13013,
 'audiences': 4799,
 'justification': 48131,
 'whatsoever': 100819,
 'depth': 20414,
 'attraction': 4663,
 'mention': 58599,
 'gross': 39302,
 'inferiority': 44712,
 'predecessor': 71367,
 'apparently': 3645,
 'cranks': 17842,
 'feel': 30168,
 'comparison': 16063,
 'unfair': 96230,
 'revisit': 76801,
 'mess': 58702,
 'akin': 2370,
 'kissing': 49061,
 'snot': 84858,
 'nosed': 64743,
 'kid': 48526,
 'acne': 480,
 'braces': 9619,
 'magic': 55806,
 'gone': 37429,
 'disturbed': 22721,
 'trust': 95116,
 'year old': 103348,
 'old girl': 65492,
 'reviewed film': 76749,
 'film brilliant': 30952,
 'better original': 7622,
 'rest assured': 76469,
 'utter rubbish': 97147,
 'little girl': 53457,
 'musical songs': 63175,
 'develop characters': 20763,
 'statement film': 86845,
 'film characters': 31010,
 'characters themes': 13362,
 'sing dance': 83949,
 'somewhat likable': 85130,
 'despite fact': 20617,
 'beautiful smart': 6565,
 'man mask': 56976,
 'slack jawed': 84308,
 'bubble gum': 10338,
 'aside pretty': 4236,
 'pretty guess': 71687,
 'didn want': 21522,
 'want mention': 98688,
 'say think': 79344,
 'think want': 92130,
 'old time': 65580,
 'old kid': 65515,
 'gone left': 37445,
 'left feeling': 50873,
 'aussie': 4851,
 'shakespeare': 82606,
 'set': 82220,
 'blood': 8637,
 'dose': 23865,
 'nudity': 64917,
 'levels': 51274,
 'cheap': 13569,
 'low': 55421,
 'budget': 10381,
 'try': 95147,
 'works': 102316,
 'sporadically': 86179,
 'macbeth': 55686,
 'lacking': 49846,
 'compelling': 16081,
 'heads': 41069,
 'especially': 27285,
 'gary': 35617,
 'sweet': 89819,
 'strangest': 88114,
 'mick': 58892,
 'molly': 59857,
 'cheese': 13688,
 'mature': 57836,
 'sam': 78693,
 'filmed': 32615,
 'western': 100767,
 'expecting': 28226,
 'romper': 77902,
 'stomper': 87235,
 'vacant': 97184,
 'effort': 25428,
 'blood blood': 8641,
 'good dose': 37609,
 'cheap low': 13593,
 'low budget': 55425,
 'try best': 95152,
 'best works': 7412,
 'good acting': 37474,
 'acting don': 641,
 'best performance': 7330,
 'performance came': 68322,
 'gary sweet': 35627,
 'like cheese': 51979,
 'love bad': 55037,
 'bad film': 5535,
 'film good': 31470,
 'expecting lot': 28239,
 'romper stomper': 77903,
 'urban': 96832,
 'cowboy': 17770,
 'ooze': 65751,
 'testosterone': 91179,
 'rodeo': 77588,
 'provide': 72596,
 'accurate': 430,
 'glimpse': 36905,
 'texas': 91188,
 'truly': 95008,
 'critique': 18273,
 'lived': 53708,
 'relative': 75776,
 'times': 93350,
 'yes': 103540,
 ...}

In [44]:
vectorizer.get_feature_names_out().tolist()[:20]

['aaa',
 'aag',
 'aaliyah',
 'aamir',
 'aamir khan',
 'aardman',
 'aaron',
 'aaron carter',
 'aaron eckhart',
 'aaron sorkin',
 'aback',
 'abandon',
 'abandoned',
 'abandoned building',
 'abandoned church',
 'abandoned film',
 'abandoned house',
 'abandoned school',
 'abandoning',
 'abandonment']

In [45]:
y.unique()

array(['positive', 'negative'], dtype=object)

In [46]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [47]:
y_train

array([0, 1, 0, ..., 0, 0, 0])

In [48]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression(solver='lbfgs',max_iter=1000,penalty='l2')
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [49]:
y_pred = model.predict(X_test)

In [50]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
print("Accuracy:", acc)

Accuracy: 0.8909579831932773

In [51]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[6597  855]
 [ 767 6656]]

In [52]:
from sklearn.metrics import classification_report

report = classification_report(y_test, y_pred, target_names=['negative', 'positive'])
print(report)

              precision    recall  f1-score   support

    negative       0.90      0.89      0.89      7452
    positive       0.89      0.90      0.89      7423

    accuracy                           0.89     14875
   macro avg       0.89      0.89      0.89     14875
weighted avg       0.89      0.89      0.89     14875

In [53]:
y_0=df.groupby('sentiment').size()
y_0

sentiment
negative    24698
positive    24884
dtype: int64

In [54]:
from sklearn.naive_bayes import MultinomialNB
modelnb = MultinomialNB(alpha=1.0)

In [55]:
modelnb.fit(X_train, y_train)
y_pred_nb = modelnb.predict(X_test)

In [56]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [57]:
print("Accuracy:", accuracy_score(y_test, y_pred_nb))
print(confusion_matrix(y_test, y_pred_nb))
print(classification_report(y_test, y_pred_nb))

Accuracy: 0.8756302521008403
[[6558  894]
 [ 956 6467]]
              precision    recall  f1-score   support

           0       0.87      0.88      0.88      7452
           1       0.88      0.87      0.87      7423

    accuracy                           0.88     14875
   macro avg       0.88      0.88      0.88     14875
weighted avg       0.88      0.88      0.88     14875